#version 450

#extension GL_GOOGLE_include_directive    : require
#extension GL_ARB_separate_shader_objects : require

#include "../include/set_bindings.glsl"
#include "../include/gpu_scene_structures.glsl"
#include "../include/depth.glsl"
#include "../include/clustered.glsl"

layout(local_size_x = 256) in;

layout(set = FRAME_SET, binding = FRAME_BINDING_CLUSTERED) uniform ClusteredUBO {
	ClusteredData clusteredData;
};

layout(set = FRAME_SET, binding = FRAME_BINDING_SCENE) uniform SceneUBO {
	SceneData scene;
};

layout(set = FRAME_SET, binding = ADDRESS_TABLE_BINDING, scalar) readonly buffer FrameAddressTableBuffer {
	GPUAddressTable frameAddressTable;
};

void main()
{
	uint visibleCount = VisibleLightCount(frameAddressTable.addrs[ABT_VisibleLightCount]).count;
	bool useClusterMajor = (visibleCount <= LIGHT_THRESHOLD);

	uint globalIndex = gl_GlobalInvocationID.x;

	// Iterate each cluster over lights
	if (useClusterMajor) {
		uint clusterIndex = globalIndex;
		uint clusterCount = clusteredData.clusterCount;
		if (clusterIndex >= clusterCount) return;

		ClusterTileSliceRanges tsrBuf =
			ClusterTileSliceRanges(frameAddressTable.addrs[ABT_ClusterTileSliceRanges]);

		ClusterCounts countsBuf =
			ClusterCounts(frameAddressTable.addrs[ABT_ClusterCounts]);

		VisibleLightIDs visibleIDsBuf =
			VisibleLightIDs(frameAddressTable.addrs[ABT_VisibleLightIDs]);

		LightBuffer lightBuf =
			LightBuffer(frameAddressTable.addrs[ABT_Lights]);

		uint tileCountX = clusteredData.tileCountX;
		uint tileCountY = clusteredData.tileCountY;
		uint tileCount  = tileCountX * tileCountY;

		uint sliceZ    = clusterIndex / tileCount;
		uint tileIndex = clusterIndex - sliceZ * tileCount;

		uint tileX = tileIndex % tileCountX;
		uint tileY = tileIndex / tileCountX;

		uvec2 tileSliceRange = tsrBuf.ranges[tileIndex];

		if (sliceZ < tileSliceRange.x || sliceZ > tileSliceRange.y || tileSliceRange.x > tileSliceRange.y) {
			countsBuf.counts[clusterIndex] = 0u;
			return;
		}

		ClusterLightIDs lightIDsBuf =
			ClusterLightIDs(frameAddressTable.addrs[ABT_ClusterLightIDs]);

		ClusterOffsets offsetsBuf =
			ClusterOffsets(frameAddressTable.addrs[ABT_ClusterOffsets]);

		ClusterCursors cursorsBuf =
			ClusterCursors(frameAddressTable.addrs[ABT_ClusterCursors]);

		uint baseOffset = offsetsBuf.offsets[clusterIndex];
		uint localCount = 0u;

		for (uint visibleIndex = 0u; visibleIndex < visibleCount; ++visibleIndex) {
			uint globalLightID = visibleIDsBuf.ids[visibleIndex];
			LocalLight light   = lightBuf.lights[globalLightID];

			if (((light.flags & LIGHT_FLAG_FLASHLIGHT_OFF) != 0u) &&
				!((light.flags & LIGHT_FLAG_CASTS_SPOT_SHADOW) != 0u) &&
				!((light.flags & LIGHT_FLAG_FLASHLIGHT) != 0u)) continue;

			LightClusterBounds lightBounds = computeLightClusterBounds(
				scene.view,
				scene.proj,
				light.position,
				light.radius,
				uvec2(scene.viewportSize.xy),
				clusteredData.tileSizeX,
				clusteredData.tileSizeY,
				clusteredData.tileCountX,
				clusteredData.tileCountY,
				clusteredData.zSlices,
				scene.cameraClips.x,
				scene.cameraClips.y
			);

			if (tileX < lightBounds.tileMin.x || tileX > lightBounds.tileMax.x) continue;
			if (tileY < lightBounds.tileMin.y || tileY > lightBounds.tileMax.y) continue;
			if (sliceZ < lightBounds.sliceMin || sliceZ > lightBounds.sliceMax) continue;

			if (localCount >= clusteredData.maxLightsPerCluster) break;

			uint writeIndex = baseOffset + localCount;
			lightIDsBuf.lightIDs[writeIndex] = globalLightID;

			localCount++;
		}
	}
	// Iterate over every light
	else {
		uint visibleIndex = globalIndex;
		if (visibleIndex >= visibleCount) return;

		VisibleLightIDs visibleIDsBuf =
			VisibleLightIDs(frameAddressTable.addrs[ABT_VisibleLightIDs]);

		uint globalLightID = visibleIDsBuf.ids[visibleIndex];

		LightBuffer lightBuf =
			LightBuffer(frameAddressTable.addrs[ABT_Lights]);

		LocalLight light = lightBuf.lights[globalLightID];

	    if (((light.flags & LIGHT_FLAG_FLASHLIGHT_OFF) != 0u) &&
		    !((light.flags & LIGHT_FLAG_CASTS_SPOT_SHADOW) != 0u) &&
		    !((light.flags & LIGHT_FLAG_FLASHLIGHT) != 0u)) return;

		LightClusterBounds lightBounds = computeLightClusterBounds(
			scene.view,
			scene.proj,
			light.position,
			light.radius,
			uvec2(scene.viewportSize.xy),
			clusteredData.tileSizeX,
			clusteredData.tileSizeY,
			clusteredData.tileCountX,
			clusteredData.tileCountY,
			clusteredData.zSlices,
			scene.cameraClips.x,
			scene.cameraClips.y
		);

		ClusterTileSliceRanges tsrBuf =
			ClusterTileSliceRanges(frameAddressTable.addrs[ABT_ClusterTileSliceRanges]);

		ClusterOffsets offsetsBuf =
			ClusterOffsets(frameAddressTable.addrs[ABT_ClusterOffsets]);

		ClusterCursors cursorsBuf =
			ClusterCursors(frameAddressTable.addrs[ABT_ClusterCursors]);

		ClusterLightIDs lightIDsBuf =
			ClusterLightIDs(frameAddressTable.addrs[ABT_ClusterLightIDs]);

		uint tileCount = clusteredData.tileCountX * clusteredData.tileCountY;

		for (uint tileY = lightBounds.tileMin.y; tileY <= lightBounds.tileMax.y; ++tileY) {
			for (uint tileX = lightBounds.tileMin.x; tileX <= lightBounds.tileMax.x; ++tileX) {

				uint tileIndex = tileY * clusteredData.tileCountX + tileX;

				uvec2 tileSliceRange = tsrBuf.ranges[tileIndex];

				uint sliceMin = max(lightBounds.sliceMin, tileSliceRange.x);
				uint sliceMax = min(lightBounds.sliceMax, tileSliceRange.y);

				if (sliceMin > sliceMax) continue;

				for (uint sliceZ = sliceMin; sliceZ <= sliceMax; ++sliceZ) {
					uint clusterIndex = sliceZ * tileCount + tileIndex;

					uint cursor = atomicAdd(cursorsBuf.cursors[clusterIndex], 1u);

					if (cursor >= clusteredData.maxLightsPerCluster) continue;

					uint writeIndex = offsetsBuf.offsets[clusterIndex] + cursor;
					lightIDsBuf.lightIDs[writeIndex] = globalLightID;
				}
			}
		}
	}
}
