#version 450

#extension GL_GOOGLE_include_directive    : require
#extension GL_ARB_separate_shader_objects : require

#include "../include/clustered.glsl"
#include "../include/common.glsl"

layout(local_size_x = 256) in;

void main()
{
	uint visibleCount = getVisibleLightCountBuffer().count;
	bool useClusterMajor = (visibleCount <= LIGHT_THRESHOLD);

	ClusteredData clustered = getClusteredData();
	SceneData scene = getSceneData();

	float camNear = scene.cameraClips.x;
	float camFar = scene.cameraClips.y;

	uint globalIndex = gl_GlobalInvocationID.x;

	// Iterate each cluster over lights
	if (useClusterMajor)
	{
		uint clusterIndex = globalIndex;
		uint clusterCount = clusteredData.clusterCount;
		if (clusterIndex >= clusterCount) return;

		ClusterTileSliceRanges tsrBuf = getClusterTileSliceRangesBuffer();
		ClusterCounts countsBuf = getClusterCountsBuffer();
		VisibleLightIDs visibleIDsBuf = getVisibleLightIDsBuffer();
		LightBuffer lightBuf = getLightBuffer();

		uint tileCountX = clusteredData.tileCountX;
		uint tileCountY = clusteredData.tileCountY;
		uint tileCount  = tileCountX * tileCountY;

		uint sliceZ    = clusterIndex / tileCount;
		uint tileIndex = clusterIndex - sliceZ * tileCount;

		uint tileX = tileIndex % tileCountX;
		uint tileY = tileIndex / tileCountX;

		uvec2 tileSliceRange = tsrBuf.ranges[tileIndex];

		if (sliceZ < tileSliceRange.x || sliceZ > tileSliceRange.y || tileSliceRange.x > tileSliceRange.y)
		{
			countsBuf.counts[clusterIndex] = 0u;
			return;
		}

		ClusterLightIDs lightIDsBuf = getClusterLightIDsBuffer();
		ClusterOffsets offsetsBuf = getClusterOffsetsBuffer();
		ClusterCursors cursorsBuf = getClusterCursorsBuffer();

		ClusterAABB box = computeClusterAABB(
			tileX, tileY, sliceZ, scene.proj, uvec2(scene.renderExtentSize.xy),
			clusteredData.tileSizeX, clusteredData.tileSizeY, clusteredData.zSlices,
			camNear, camFar);

		uint baseOffset = offsetsBuf.offsets[clusterIndex];
		uint localCount = 0u;

		for (uint visibleIndex = 0u; visibleIndex < visibleCount; ++visibleIndex)
		{
			uint globalLightID = visibleIDsBuf.ids[visibleIndex];
			LocalLight light   = lightBuf.lights[globalLightID];

			if (((light.flags & LIGHT_FLAG_FLASHLIGHT_OFF) != 0u) &&
				!((light.flags & LIGHT_FLAG_CASTS_SPOT_SHADOW) != 0u) &&
				!((light.flags & LIGHT_FLAG_FLASHLIGHT) != 0u)) continue;

			vec3 lightVS = (scene.view * vec4(light.position, 1.0)).xyz;
			if (!sphereOverlapsCluster(lightVS, light.radius, box)) continue;

			if (localCount >= clusteredData.maxLightsPerCluster) break;

			uint writeIndex = baseOffset + localCount;
			lightIDsBuf.lightIDs[writeIndex] = globalLightID;

			localCount++;
		}
	}
	// Iterate over every light
	else
	{
		uint visibleIndex = globalIndex;
		if (visibleIndex >= visibleCount) return;

		VisibleLightIDs visibleIDsBuf = getVisibleLightIDsBuffer();

		uint globalLightID = visibleIDsBuf.ids[visibleIndex];

		LightBuffer lightBuf = getLightBuffer();

		LocalLight light = lightBuf.lights[globalLightID];

		if (((light.flags & LIGHT_FLAG_FLASHLIGHT_OFF) != 0u) &&
			!((light.flags & LIGHT_FLAG_CASTS_SPOT_SHADOW) != 0u) &&
			!((light.flags & LIGHT_FLAG_FLASHLIGHT) != 0u)) return;

		LightClusterBounds lightBounds = computeLightClusterBounds(
			scene.view,
			scene.proj,
			light.position,
			light.radius,
			uvec2(scene.renderExtentSize.xy),
			clusteredData.tileSizeX,
			clusteredData.tileSizeY,
			clusteredData.tileCountX,
			clusteredData.tileCountY,
			clusteredData.zSlices,
			camNear,
			camFar);

		ClusterTileSliceRanges tsrBuf = getClusterTileSliceRangesBuffer();

		ClusterOffsets offsetsBuf = getClusterOffsetsBuffer();

		ClusterCursors cursorsBuf = getClusterCursorsBuffer();

		ClusterLightIDs lightIDsBuf = getClusterLightIDsBuffer();

		uint tileCount = clusteredData.tileCountX * clusteredData.tileCountY;

		for (uint tileY = lightBounds.tileMin.y; tileY <= lightBounds.tileMax.y; ++tileY)
		{
			for (uint tileX = lightBounds.tileMin.x; tileX <= lightBounds.tileMax.x; ++tileX)
			{

				uint tileIndex = tileY * clusteredData.tileCountX + tileX;

				uvec2 tileSliceRange = tsrBuf.ranges[tileIndex];

				uint sliceMin = max(lightBounds.sliceMin, tileSliceRange.x);
				uint sliceMax = min(lightBounds.sliceMax, tileSliceRange.y);

				if (sliceMin > sliceMax) continue;

				for (uint sliceZ = sliceMin; sliceZ <= sliceMax; ++sliceZ)
				{
					uint clusterIndex = sliceZ * tileCount + tileIndex;

					uint cursor = atomicAdd(cursorsBuf.cursors[clusterIndex], 1u);

					if (cursor >= clusteredData.maxLightsPerCluster) continue;

					uint writeIndex = offsetsBuf.offsets[clusterIndex] + cursor;
					lightIDsBuf.lightIDs[writeIndex] = globalLightID;
				}
			}
		}
	}
}
