#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_ARB_separate_shader_objects : require

// Ideas and most code pulled from here, thanks Will
// https://github.com/Williscool13/WillEngineV2/blob/87a90f41f0486acfd6a589346b919f3bc9629172/shaders/ambient_occlusion/ground_truth/gtao_main_pass.comp

// Original XE_GTAO implementation
// https://github.com/GameTechDev/XeGTAO/blob/master/Source/Rendering/Shaders/XeGTAO.hlsli

// The original GTAO paper
// https://www.iryoku.com/downloads/Practical-Realtime-Strategies-for-Accurate-Indirect-Occlusion.pdf

#include "../include/set_bindings.glsl"
#include "../include/depth.glsl"
#include "../include/gpu_scene_structures.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

const float XE_GTAO_PI = 3.1415926535897932384626433832795;
const float XE_GTAO_HALF_PI = 1.5707963267948966192313216916398;

// Depth pyramid texture
layout(set = PUSH_SET, binding = PUSH_BINDING_DEPTH_TEX) uniform sampler2D depthPyramid;

// Normal texture
layout(set = PUSH_SET, binding = PUSH_BINDING_NORMAL_TEX) uniform sampler2D normal;

// Noise texture
layout(set = PUSH_SET, binding = PUSH_BINDING_NOISE_TEX) uniform sampler2D noiseTex;

// GTAO outputs
layout(set = PUSH_SET, binding = PUSH_BINDING_OUTPUT_1_TEX) writeonly uniform image2D rawAO;
layout(set = PUSH_SET, binding = PUSH_BINDING_OUTPUT_3_TEX) writeonly uniform image2D edgeInfo;

layout(set = FRAME_SET, binding = FRAME_BINDING_SCENE) uniform SceneUBO {
	SceneData scene;
};

layout(push_constant) uniform GTAOPush {
	vec2 ndcToViewMul;
	vec2 tanHalfFov;

	vec2 ndcToViewAdd;
	vec2 pixelSize;

	float effectRadius;
	float radiusMultiplier;
	float effectFalloffRange;
	float sampleDistributionPower;

	float thinOccluderCompensation;
	float depthMipSamplingOffset;
	vec2 ndcToViewMul_x_PixelSize;

	uint sliceCount;
	uint stepsPerSliceCount;
	float sharpness;
	float radius;

	vec2 blurDirection;
	vec2 pad0;
} pc;

// https://h14s.p5r.org/2012/09/0x5f3759df.html
float fastSqrt(float x) {
	return uintBitsToFloat(0x1fbd1df5 + (floatBitsToUint(x) >> 1));
}

// [-1, 1] -> [0, PI]
float fastAcos(float inX) {
	const float PI = 3.141593;
	const float HALF_PI = 1.570796;
	float x = abs(inX);
	float r = -0.156583 * x + HALF_PI;
	r *= fastSqrt(1.0 - x);

	return (inX >= 0.0) ? r : (PI - r);
}

vec3 reconstructViewPos(vec2 uv, float depthVS) {
	// Cheap mode used by XEGTAO
	vec3 pos;
	pos.xy = (pc.ndcToViewMul * uv + pc.ndcToViewAdd) * depthVS;
	pos.z = -depthVS;
	return pos;
}

vec4 computeEdges(float center, float left, float right, float top, float bottom) {
	vec4 dz = vec4(left, right, top, bottom) - vec4(center);

	float slopeLR = 0.5 * (dz.y - dz.x);
	float slopeTB = 0.5 * (dz.w - dz.z);

	vec4 dz2 = dz + vec4(slopeLR, -slopeLR, slopeTB, -slopeTB);
	dz = min(abs(dz), abs(dz2));

	return clamp((1.25 - dz / (center * 0.011)), 0.0, 1.0);
}

// 2 bits per edge mean 4 gradient values (0, 0.33, 0.66, 1) for smoother transitions!
float packEdges(vec4 edges)
{
	edges = round(clamp(edges, 0, 1) * 2.9);
	return dot(edges, vec4(64.0 / 255.0, 16.0 / 255.0, 4.0 / 255.0, 1.0 / 255.0));
}

vec2 getNoise(ivec2 pix) {
	ivec2 noiseCoord = pix % ivec2(4, 4);
	return texture(noiseTex, (vec2(noiseCoord) + 0.5) / 4.0).rg;
}

//mat3 rotFromTo(vec3 from, vec3 to)
//{
//	float cosA = clamp(dot(from, to), -1.0, 1.0);
//	vec3 v = cross(from, to);
//	float s = length(v);
//
//	// If vectors are almost parallel or anti-parallel, bail out
//	if (s < 1e-5) {
//		return mat3(1.0);
//	}
//
//	vec3 axis = v / s;
//	float t = 1.0 - cosA;
//
//	float x = axis.x;
//	float y = axis.y;
//	float z = axis.z;
//
//	// Row entries r_ij:
//	float r00 = t*x*x + cosA;
//	float r01 = t*x*y - s*z;
//	float r02 = t*x*z + s*y;
//
//	float r10 = t*x*y + s*z;
//	float r11 = t*y*y + cosA;
//	float r12 = t*y*z - s*x;
//
//	float r20 = t*x*z - s*y;
//	float r21 = t*y*z + s*x;
//	float r22 = t*z*z + cosA;
//
//	return mat3(
//		r00, r10, r20,
//		r01, r11, r21,
//		r02, r12, r22
//	);
//}

void main()
{
	const ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = (vec2(pix) + 0.5) * pc.pixelSize;

	vec2 gatherCenter = vec2(pix) * pc.pixelSize;
	vec4 UL = textureGather(depthPyramid, gatherCenter, 0);
	vec4 BR = textureGatherOffset(depthPyramid, gatherCenter, ivec2(1, 1), 0);

	// In view space
	float centerZ      = UL.y;
	const float leftZ  = UL.x;
	const float topZ   = UL.z;
	const float rightZ = BR.z;
	const float botZ   = BR.x;

	// Edge detection
	vec4 edges = computeEdges(centerZ, leftZ, rightZ, topZ, botZ);
	float packed = packEdges(edges);
	imageStore(edgeInfo, pix, vec4(packed));

	// View space normals
	vec3 N = normalize(texture(normal, uv).rgb * 2.0 - 1.0);

	// Per Intel: Moves center pixel a bit to avoid imprecision artifacts.
	centerZ *= 0.99920;

	// Reconstruct view space pos
	vec3 vPos = reconstructViewPos(uv, centerZ);
	vec3 viewVec = normalize(-vPos);

	// centerZ is your positive view-space depth
	float depthVS = centerZ;

	// Depth fade for GTAO
	float depthFade = 1.0;
	float maxDepth = 30.0;
	float fadeStart = maxDepth * 0.7;  // start fading at 70% of range

	if (depthVS > fadeStart) {
		float t = clamp((depthVS - fadeStart) / (maxDepth - fadeStart), 0.0, 1.0);
		depthFade = 1.0 - t;
		if (depthFade <= 0.0) {
			// Completely outside GTAO range: no occlusion
			imageStore(rawAO, pix, vec4(1.0));
			return;
		}
	}

	// GTAO sampling parameters
	const float effectRadius = pc.effectRadius * pc.radiusMultiplier;
	const float falloffRange = pc.effectFalloffRange * effectRadius;
	const float falloffFrom = effectRadius * (1.0 - pc.effectFalloffRange);

	const float falloffMul = -1.0 / falloffRange;
	const float falloffAdd = falloffFrom / falloffRange + 1.0;

	float visibility = 0.0;

	// 4x4 noise
	vec2 noise = getNoise(pix);
	float noiseSlice = noise.x;
	float noiseSample = noise.y;

	const vec2 pixelDirRBViewSpaceSizeAtCenterZ = vec2(centerZ) * pc.ndcToViewMul_x_PixelSize;

	float screenspaceRadius = effectRadius / pixelDirRBViewSpaceSizeAtCenterZ.x;

	// Raidus too small -> early exits
	const float pixelTooCloseThreshold = 1.3;

	visibility += clamp((10.0 - screenspaceRadius) / 100.0, 0.0, 1.0) * 0.5;

	if (screenspaceRadius < pixelTooCloseThreshold) {
		visibility = clamp(visibility, 0.0, 1.0);

		imageStore(rawAO, pix, vec4(visibility));
		return;
	}

	// Minimal sample offset to avoid sampling center
	const float minS = pixelTooCloseThreshold / screenspaceRadius;

	// Define hemisphere slices for outer loop
	const float sliceCount = float(pc.sliceCount);
	const float stepsPerSlice = float(pc.stepsPerSliceCount);
	for (float slice = 0.0; slice < sliceCount; slice++) {
		float sliceK = (slice + noiseSlice) / sliceCount;

		// Slice direction angle
		float phi = sliceK * XE_GTAO_PI;
		float cosPhi = cos(phi);
		float sinPhi = sin(phi);

		vec2 omega = vec2(cosPhi, -sinPhi) * screenspaceRadius;
		const vec3 dirVec = vec3(cosPhi, sinPhi, 0.0);

		// Orthogonal projection basis
		const vec3 orthoDirVec = dirVec - (dot(dirVec, viewVec) * viewVec);
		const vec3 axisVec = normalize(cross(orthoDirVec, viewVec));

		vec3 projectedNormalVec = N - axisVec * dot(N, axisVec);
		float signNorm = sign(dot(orthoDirVec, projectedNormalVec));

		float projectedNormalLength = length(projectedNormalVec);
		float cosNorm = clamp(dot(projectedNormalVec, viewVec) / projectedNormalLength, 0.0, 1.0);

		float n = signNorm * fastAcos(cosNorm);

		const float lowHorizonCos0 = cos(n + XE_GTAO_HALF_PI);
		const float lowHorizonCos1 = cos(n - XE_GTAO_HALF_PI);

		float horizonCos0 = lowHorizonCos0;
		float horizonCos1 = lowHorizonCos1;

		// Inner loop ray march along slice direction
		for (float step = 0.0; step < stepsPerSlice; step++) {
			// R1 quasi-random progression
			const float stepBaseNoise = (slice + step * stepsPerSlice) * 0.61803398874989484;
			float stepNoise = fract(noiseSample + stepBaseNoise);

			float s = (step + stepNoise) / stepsPerSlice;
			s = pow(s, pc.sampleDistributionPower);

			// Avoids sampling middle pixel
			s += minS;

			vec2 sampleOffset = s * omega;
			float sampleOffsetLength = length(sampleOffset);

			// Snap pixel to center to avoid artifacts
			sampleOffset = round(sampleOffset) * pc.pixelSize;

			// Sample + opposite sample
			vec2 sampleScreenPos0 = uv + sampleOffset;
			vec2 sampleScreenPos1 = uv - sampleOffset;

			// Selected mip level in depth pyramid
			const float mipLevel = clamp(log2(sampleOffsetLength) - pc.depthMipSamplingOffset, 0.0, float(HI_Z_MIP_COUNT));

			float SZ0 = textureLod(depthPyramid, sampleScreenPos0, mipLevel).r;
			float SZ1 = textureLod(depthPyramid, sampleScreenPos1, mipLevel).r;

			vec3 samplePos0 = reconstructViewPos(sampleScreenPos0, SZ0);
			vec3 samplePos1 = reconstructViewPos(sampleScreenPos1, SZ1);

			vec3 delta0 = samplePos0 - vPos;
			vec3 delta1 = samplePos1 - vPos;
			float dist0 = length(delta0);
			float dist1 = length(delta1);

			vec3 horizonVec0 = delta0 / dist0;
			vec3 horizonVec1 = delta1 / dist1;

			// Thickness heuristic
			float falloffBase0 = length(vec3(delta0.x, delta0.y, delta0.z * (1.0 + pc.thinOccluderCompensation)));
			float falloffBase1 = length(vec3(delta1.x, delta1.y, delta1.z * (1.0 + pc.thinOccluderCompensation)));
			float weight0 = clamp(falloffBase0 * falloffMul + falloffAdd, 0.0, 1.0);
			float weight1 = clamp(falloffBase1 * falloffMul + falloffAdd, 0.0, 1.0);

			// Sample horizon cos
			float shc0 = dot(horizonVec0, viewVec);
			float shc1 = dot(horizonVec1, viewVec);

			// Discard unwanted samples
			shc0 = mix(lowHorizonCos0, shc0, weight0);
			shc1 = mix(lowHorizonCos1, shc1, weight1);

			horizonCos0 = max(horizonCos0, shc0);
			horizonCos1 = max(horizonCos1, shc1);
		}

		// Slant correction hack
		projectedNormalLength = mix(projectedNormalLength, 1.0, 0.05);

		// Integrate visibility from horizon angles
		float h0 = -fastAcos(horizonCos1);
		float h1 = fastAcos(horizonCos0);
		float iarc0 = (cosNorm + 2.0 * h0 * sin(n) - cos(2.0 * h0 - n)) / 4.0;
		float iarc1 = (cosNorm + 2.0 * h1 * sin(n) - cos(2.0 * h1 - n)) / 4.0;
		float localVisibility = projectedNormalLength * (iarc0 + iarc1);
		visibility += localVisibility;

//		// Bent normals integration (XEGTAO Algorithm 2)
//		float t0 = (6.0 * sin(h0 - n)
//				  - sin(3.0 * h0 - n)
//				  + 6.0 * sin(h1 - n)
//				  - sin(3.0 * h1 - n)
//				  + 16.0 * sin(n)
//				  - 3.0 * (sin(h0 + n) + sin(h1 + n))) / 12.0;
//
//		float t1 = (-cos(3.0 * h0 - n)
//				   - cos(3.0 * h1 - n)
//				   + 8.0 * cos(n)
//				   - 3.0 * (cos(h0 + n) + cos(h1 + n))) / 12.0;
//
//		// local bent normal in slice direction
//		vec3 localBent = vec3(
//			dirVec.x * t0,
//			dirVec.y * t0,
//			-t1
//		);
//
//		// rotate hemisphere normal (-Z) into viewVec space
//		mat3 rot = rotFromTo(vec3(0,0,-1), viewVec);
//
//		// Apply slice scaling from projected normal
//		vec3 bentRot = rot * localBent * projectedNormalLength;
//
//		bentNormal += bentRot * localVisibility;
	}

	// Normalize
	visibility /= sliceCount;

	// Nonlinear mapping
	visibility = pow(visibility, 2.2);
	visibility = max(0.03, visibility); // avoid pure black

	visibility = clamp(visibility, 0.0, 1.0);

	visibility = mix(1.0, visibility, depthFade);

	imageStore(rawAO, pix, vec4(visibility));
}