#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_ARB_separate_shader_objects : require

// Original XE_GTAO implementation
// https://github.com/GameTechDev/XeGTAO/blob/master/Source/Rendering/Shaders/XeGTAO.hlsli

#include "../include/common.glsl"
#include "../include/depth.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D inDepthResolved;

layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1) writeonly uniform image2D outMip0;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_2) writeonly uniform image2D outMip1;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_3) writeonly uniform image2D outMip2;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_4) writeonly uniform image2D outMip3;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_5) writeonly uniform image2D outMip4;

layout(push_constant) uniform PushConstantData {
	vec2 tanHalfFov;
	float effectRadius;
	float effectFalloffRange;

	vec2 ndcToViewAdd;
	vec2 ndcToViewMul;

	vec2 ndcToViewMul_x_PixelSize;
	float depthLinearizeMult;
	float depthLinearizeAdd;
} pc;

shared float g_scratch[8][8];

float screenToViewSpaceDepth(float screenDepth) {
	// Optimization by XeGTAO
	// https://github.com/GameTechDev/XeGTAO/blob/a5b1686c7ea37788eeb3576b5be47f7c03db532c/Source/Rendering/Shaders/XeGTAO.hlsli#L112
	return pc.depthLinearizeMult / (pc.depthLinearizeAdd - screenDepth);
}

float depthMIPFilter(float d0, float d1, float d2, float d3) {
	float maxD = max(max(d0, d1), max(d2, d3));

	const float depthRangeScale = 0.75;
	float effectRadius = depthRangeScale * pc.effectRadius * GTAO_RADIUS_MULTIPLIER;
	float falloffRange = pc.effectFalloffRange * effectRadius;
	float falloffFrom  = effectRadius * (1.0 - pc.effectFalloffRange);
	float falloffMul   = -1.0 / falloffRange;
	float falloffAdd   = falloffFrom / falloffRange + 1.0;

	float w0 = saturate((maxD - d0) * falloffMul + falloffAdd);
	float w1 = saturate((maxD - d1) * falloffMul + falloffAdd);
	float w2 = saturate((maxD - d2) * falloffMul + falloffAdd);
	float w3 = saturate((maxD - d3) * falloffMul + falloffAdd);

	return (w0*d0 + w1*d1 + w2*d2 + w3*d3) / (w0+w1+w2+w3);
}

void main() {
	uvec2 tid  = gl_LocalInvocationID.xy;
	uvec2 base = gl_GlobalInvocationID.xy;

	SceneData scene = getSceneData();
	const vec2 fullPixelSize = vec2(scene.pixelSizes.xy);

	// MIP0
	uvec2 pixCoord = base * 2u;
	vec2  uv = (vec2(pixCoord) * 0.5) * fullPixelSize;

	vec4 depths = textureGatherOffset(inDepthResolved, vec2(pixCoord) * fullPixelSize, ivec2(1), 0);
	float d0 = screenToViewSpaceDepth(depths.w);
	float d1 = screenToViewSpaceDepth(depths.z);
	float d2 = screenToViewSpaceDepth(depths.x);
	float d3 = screenToViewSpaceDepth(depths.y);

	imageStore(outMip0, ivec2(pixCoord) + ivec2(0,0), vec4(d0));
	imageStore(outMip0, ivec2(pixCoord) + ivec2(1,0), vec4(d1));
	imageStore(outMip0, ivec2(pixCoord) + ivec2(0,1), vec4(d2));
	imageStore(outMip0, ivec2(pixCoord) + ivec2(1,1), vec4(d3));

	// MIP1
	float dm1 = depthMIPFilter(d0, d1, d2, d3);
	imageStore(outMip1, ivec2(base), vec4(dm1));
	g_scratch[tid.x][tid.y] = dm1;

	memoryBarrierShared();
	barrier();

	// MIP2
	if (all(equal(tid.xy % 2u, uvec2(0u)))) {
		float inTL = g_scratch[tid.x+0][tid.y+0];
		float inTR = g_scratch[tid.x+1][tid.y+0];
		float inBL = g_scratch[tid.x+0][tid.y+1];
		float inBR = g_scratch[tid.x+1][tid.y+1];
		float dm2 = depthMIPFilter(inTL, inTR, inBL, inBR);
		imageStore(outMip2, ivec2(base / 2u), vec4(dm2));
		g_scratch[tid.x][tid.y] = dm2;
	}

	memoryBarrierShared();
	barrier();

	// MIP3
	if (all(equal(tid.xy % 4u, uvec2(0u)))) {
		float inTL = g_scratch[tid.x+0][tid.y+0];
		float inTR = g_scratch[tid.x+2][tid.y+0];
		float inBL = g_scratch[tid.x+0][tid.y+2];
		float inBR = g_scratch[tid.x+2][tid.y+2];
		float dm3 = depthMIPFilter(inTL, inTR, inBL, inBR);
		imageStore(outMip3, ivec2(base / 4u), vec4(dm3));
		g_scratch[tid.x][tid.y] = dm3;
	}

	memoryBarrierShared();
	barrier();

	// MIP4
	if (all(equal(tid.xy % 8u, uvec2(0u)))) {
		float inTL = g_scratch[tid.x+0][tid.y+0];
		float inTR = g_scratch[tid.x+4][tid.y+0];
		float inBL = g_scratch[tid.x+0][tid.y+4];
		float inBR = g_scratch[tid.x+4][tid.y+4];
		float dm4 = depthMIPFilter(inTL, inTR, inBL, inBR);
		imageStore(outMip4, ivec2(base / 8u), vec4(dm4));
	}
}
