#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_ARB_separate_shader_objects : require

#include "../include/common.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D opaqueHDR;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_2) uniform sampler2D transparentAccum;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_3) uniform sampler2D transparentRevealage;

layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1) writeonly uniform image2D hdrSceneComposite;

void main()
{
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 dim   = imageSize(hdrSceneComposite);
	if (any(greaterThanEqual(coord, dim))) return;

	vec4 opaque = texelFetch(opaqueHDR, coord, 0);

	vec4  accum  = texelFetch(transparentAccum, coord, 0);
	float reveal = texelFetch(transparentRevealage, coord, 0).r;

	if (reveal >= 0.9999)
	{
		imageStore(hdrSceneComposite, coord, opaque);
		return;
	}

	vec3 transparentColor = accum.rgb / max(accum.a, 1e-5);
	float transparentAlpha = 1.0 - reveal;

	vec3 sceneColor =
		transparentColor * transparentAlpha +
		opaque.rgb * reveal;

	imageStore(hdrSceneComposite, coord, vec4(sceneColor, opaque.a));
}
