#version 460

#extension GL_GOOGLE_include_directive : require

#include "../include/rt_shadow_common.glsl"
#include "../include/nrd_common.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D uDepth;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_2) uniform sampler2D uViewNormals;

layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1, r32f) uniform writeonly image2D uPenumbraOut;

const int SHADOW_TAPS = 1;

void main()
{
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);

	if (any(greaterThanEqual(px, ivec2(sp.resolution)))) return;

	SceneData sd = getSceneData();

	float depth = texelFetch(uDepth, px, 0).r;

	if (depth <= DEPTH_EPSILON_REVERSED_Z)
	{
		imageStore(
			uPenumbraOut,
			px,
			vec4(SIGMA_FrontEnd_PackPenumbra(
				NRD_FP16_MAX,
				TAN_SUN_ANGULAR_RADIUS)));
		return;
	}

	vec3 nVS = octDecode(texelFetch(uViewNormals, px, 0).rg * 2.0 - 1.0);

	if (dot(nVS, sp.shadow.sunDirectionVS) <= 0.0)
	{
		imageStore(
			uPenumbraOut,
			px,
			vec4(SIGMA_FrontEnd_PackPenumbra(
				0.0,
				TAN_SUN_ANGULAR_RADIUS)));
		return;
	}

	vec2 uv = (vec2(px) + 0.5) * sp.invResolution;

	ViewReconstructResult vr =
		reconstructWorldPosFromDepth(
			uv,
			depth,
			sd.invProj,
			sd.invView);

	vec3 N = mat3(sd.invView) * nVS;

	vec3 origin =
		vr.pos +
		N * rtSurfaceBias(
			sp.shadow,
			vr.viewDepth);

	vec2 rnd =
		rtNoise(
			px,
			sp.hilbertLutID,
			sd.temporal.x,
			RT_NOISE_OFFSET_SHADOW);

	RTVisibility v =
		rtConeVisibilityRnd(
			origin,
			normalize(sd.sunlightDirection.xyz),
			TAN_SUN_ANGULAR_RADIUS,
			rnd,
			SHADOW_TAPS,
			sp.shadow.rayTMin,
			sp.shadow.rayTMax,
			sp.shadow.mipBias,
			sp.shadow.alphaTested != 0u);

	float distanceToOccluder =
		v.hits > 0.0
			? v.occluderDist
			: NRD_FP16_MAX;

	imageStore(
		uPenumbraOut,
		px,
		vec4(SIGMA_FrontEnd_PackPenumbra(
			distanceToOccluder,
			TAN_SUN_ANGULAR_RADIUS)));
}
