#version 450

#extension GL_ARB_separate_shader_objects : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_buffer_reference : require

#include "../include/set_bindings.glsl"
#include "../include/gpu_scene_structures.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = GLOBAL_SET, binding = ADDRESS_TABLE_BINDING, scalar) buffer GlobalAddressTableBuffer {
	GPUAddressTable globalAddressTable;
};

layout(set = FRAME_SET, binding = FRAME_BINDING_SCENE) uniform SceneUBO {
	SceneData scene;
};

layout(set = PUSH_SET, binding = PUSH_BINDING_INPUT_1_TEX) uniform sampler2D opaqueImage;
layout(set = PUSH_SET, binding = PUSH_BINDING_INPUT_2_TEX) uniform sampler2D transparentImage;

shared float localLuminance[gl_WorkGroupSize.x * gl_WorkGroupSize.y];

void main()
{
	ivec2 opaqueSize = textureSize(opaqueImage, 0);
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);

	if (coord.x >= opaqueSize.x || coord.y >= opaqueSize.y) return;

	// Combine and convert to luminance
	vec3 hdrOpaque = texelFetch(opaqueImage, coord, 0).rgb;
	vec3 hdrTransparent = texelFetch(transparentImage, coord, 0).rgb;
	vec3 hdr = max(hdrOpaque + hdrTransparent, 0.0);

	float Y = max(dot(hdr, vec3(0.2126, 0.7152, 0.0722)), 1e-4);
	float logY = log(Y);

	uint lid = gl_LocalInvocationIndex;
	localLuminance[lid] = logY;
	barrier();

	for (uint stride = (gl_WorkGroupSize.x * gl_WorkGroupSize.y) >> 1; stride > 0; stride >>= 1) {
		if (lid < stride)
			localLuminance[lid] += localLuminance[lid + stride];
		barrier();
	}

	if (lid == 0) {
		uint groupIndex = gl_WorkGroupID.y * gl_NumWorkGroups.x + gl_WorkGroupID.x;

		LuminanceBuffer lBuf = LuminanceBuffer(globalAddressTable.addrs[ABT_Luminance]);
		lBuf.luminanceSums[groupIndex] = vec4(localLuminance[0], 0.0, 0.0, 0.0);
	}
}