#version 450

#extension GL_ARB_separate_shader_objects : require
#extension GL_GOOGLE_include_directive : require

#include "../include/common.glsl"

// Amazing resource on why exposure is important
// https://bruop.github.io/exposure/

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D opaqueImage;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_2) uniform sampler2D transparentImage;

shared float localLuminance[gl_WorkGroupSize.x * gl_WorkGroupSize.y];

void main()
{
	ivec2 opaqueSize = textureSize(opaqueImage, 0);
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);

	if (coord.x >= opaqueSize.x || coord.y >= opaqueSize.y) return;

	// Combine and convert to luminance
	vec3 hdrOpaque = texelFetch(opaqueImage, coord, 0).rgb;
	vec3 hdrTransparent = texelFetch(transparentImage, coord, 0).rgb;
	vec3 hdr = max(hdrOpaque + hdrTransparent, 0.0);

	float Y = luminance(hdr);
	float logY = log(Y);

	uint lid = gl_LocalInvocationIndex;
	localLuminance[lid] = logY;
	barrier();

	for (uint stride = (gl_WorkGroupSize.x * gl_WorkGroupSize.y) >> 1; stride > 0; stride >>= 1) {
		if (lid < stride)
			localLuminance[lid] += localLuminance[lid + stride];
		barrier();
	}

	if (lid == 0) {
		uint groupIndex = gl_WorkGroupID.y * gl_NumWorkGroups.x + gl_WorkGroupID.x;

		LuminanceBuffer lBuf = getLuminanceBuffer();
		lBuf.luminanceSums[groupIndex] = vec4(localLuminance[0], 0.0, 0.0, 0.0);
	}
}
