#version 450

#extension GL_ARB_separate_shader_objects : require
#extension GL_GOOGLE_include_directive : require

#include "../include/common.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D opaqueImage;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_2) uniform sampler2D transparentImage;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_3) uniform sampler2D volumetricLightImage;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_4) uniform sampler2D lensFlareColorImage;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1) writeonly uniform image2D toneMapImage;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_2) writeonly uniform image2D cmaa2ColorImage;

vec3 ACESFilm(vec3 x) {
	const float a = 2.51;
	const float b = 0.03;
	const float c = 2.43;
	const float d = 0.59;
	const float e = 0.14;
	return clamp((x * (a * x + b)) / (x *(c * x + d) + e), 0.0, 1.0);
}

float noiseHash(ivec2 p)
{
	return fract(sin(dot(vec2(p), vec2(12.9898, 78.233))) * 43758.5453);
}

void main()
{
	ivec2 dim = imageSize(toneMapImage);
	ivec2 pid = ivec2(gl_GlobalInvocationID.xy);
	if (any(greaterThanEqual(pid, dim))) return;

	vec2 uvFull = (vec2(pid) + 0.5) / vec2(dim);

	vec3 hdrOpaque = texelFetch(opaqueImage, pid, 0).rgb;
	vec3 hdrTransparent = texelFetch(transparentImage, pid, 0).rgb;
	vec3 hdrScene = hdrOpaque + hdrTransparent;

	vec3 volumetricLight = texture(volumetricLightImage, uvFull).rgb;

	vec3 lensFlare = vec3(0.0);
	if (DBG(enableLensFlare)) {
		ivec2 flareDim = textureSize(lensFlareColorImage, 0);
		vec2 uvFlare = (uvFull * vec2(flareDim) + 0.5) / vec2(flareDim);
		lensFlare = textureLod(lensFlareColorImage, uvFlare, 0.0).rgb;
	}

	vec3 hdr = max(hdrScene + volumetricLight + lensFlare, 0.0);

	float exposure = getLuminanceBuffer().luminanceSums[0].x;
	exposure = max(exposure, 1e-4);

	vec3 mapped = ACESFilm(hdr * exposure);
	float noise = noiseHash(pid);
	mapped += (noise - 0.5) / 2048.0;

	imageStore(toneMapImage, pid, vec4(mapped, 1.0));

	if (debug.aaMode == AA_CMAA2) {
		imageStore(cmaa2ColorImage, pid, vec4(mapped, 1.0));
	}
}
