#version 450

#extension GL_ARB_separate_shader_objects : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_GOOGLE_include_directive : require

#include "../include/set_bindings.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_INPUT_TEX) uniform sampler2D drawImage;
layout(set = PUSH_SET, binding = PUSH_BINDING_OUTPUT_TEX) uniform writeonly image2D toneMap;

layout(push_constant) uniform PC {
	float brightness;
	float saturation;
	float contrast;
	float pad0;
} pc;

void main() {
	uvec2 texelCoord = gl_GlobalInvocationID.xy;

	ivec2 size = imageSize(toneMap);
	if (texelCoord.x >= uint(size.x) || texelCoord.y >= uint(size.y)) return;

	vec2 uv = vec2(texelCoord) / vec2(size);

	vec4 color = texture(drawImage, uv);

	color.rgb *= pc.brightness;
	color.rgb = clamp(color.rgb, 0.0, 1.0);
	color.rgb = pow(color.rgb, vec3(0.8)); // Adjust tone

	float gray = dot(color.rgb, vec3(0.299, 0.587, 0.114));
	color.rgb = mix(vec3(gray), color.rgb, pc.saturation);

	color.rgb = (color.rgb - 0.5) * pc.contrast + 0.5;

	imageStore(toneMap, ivec2(texelCoord), color);
}