#version 450

#extension GL_ARB_separate_shader_objects : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_GOOGLE_include_directive : require

#include "../include/set_bindings.glsl"

layout (local_size_x = 8, local_size_y = 8) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_INPUT_1_TEX) uniform samplerCube skyboxImage;
layout(set = PUSH_SET, binding = PUSH_BINDING_OUTPUT_TEX) writeonly uniform image2DArray irradianceStorage;

const float PI = 3.14159265359;

layout(push_constant) uniform EnvData {
	float sampleCountF;
	uint sampleCountU;
	uint pad0[2];
} pc;

void main()
{
	ivec3 storePos = ivec3(gl_GlobalInvocationID.xy, gl_GlobalInvocationID.z);
	vec2 uv = (vec2(storePos.xy) + 0.5) / vec2(imageSize(irradianceStorage).xy); // Normalized coordinates

	uv = uv * 2.0 - 1.0; // Map to range [-1, 1]

	vec3 direction;
	switch (storePos.z) {
		case 0: direction = normalize(vec3(1.0,   -uv.y, -uv.x)); break; // +X
		case 1: direction = normalize(vec3(-1.0,  -uv.y,  uv.x)); break; // -X
		case 2: direction = normalize(vec3(uv.x,   1.0,   uv.y)); break; // +Y
		case 3: direction = normalize(vec3(uv.x,  -1.0,  -uv.y)); break; // -Y
		case 4: direction = normalize(vec3(uv.x,  -uv.y,  1.0));  break; // +Z
		case 5: direction = normalize(vec3(-uv.x, -uv.y, -1.0));  break; // -Z
		default: direction = vec3(0.0); break; // Should not happen
	}

	vec3 irradiance = vec3(0.0);

	// Convolution Code
	vec3 up = vec3(0.0, 1.0, 0.0);
	if (abs(direction.y) > 0.999) { // Handle parallel case
		up = vec3(0.0, 0.0, 1.0);
	}
	vec3 right = normalize(cross(up, direction));
	up = normalize(cross(direction, right));

	float sampleDelta = pc.sampleCountF;
	float nrSamples = 0.0;
	for(float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta)
	{
		for(float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta)
		{
			// spherical to cartesian (in tangent space)
			vec3 tangentSample = vec3(sin(theta) * cos(phi),  sin(theta) * sin(phi), cos(theta));
			// tangent space to world
			vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * direction;

			vec3 sampleColor = texture(skyboxImage, sampleVec).rgb;

			irradiance += sampleColor * cos(theta) * sin(theta);

			nrSamples++;
		}
	}

	irradiance = PI * irradiance * (1.0 / float(nrSamples));
	irradiance = pow(irradiance, vec3(1.0 / 1.2));
	vec4 out_irradiance = vec4(irradiance, 1.0);
	imageStore(irradianceStorage, storePos, out_irradiance);
}