#version 450

#extension GL_ARB_separate_shader_objects : require
#extension GL_GOOGLE_include_directive : require

#include "../include/common.glsl"

layout (local_size_x = 16, local_size_y = 16) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D equirectImage;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1) writeonly uniform image2DArray skyboxStorage;


vec2 SampleSphericalMap(vec3 v) {
	vec2 invAtan = vec2(0.1591, 0.3183); // 1 / (2 * pi), 1 / pi
	vec2 uv = vec2(atan(v.z, v.x), asin(v.y));
	uv *= invAtan;
	uv += 0.5;
	return uv;
}

void main() {
	ivec3 storePos = ivec3(gl_GlobalInvocationID.xy, gl_GlobalInvocationID.z);
	vec2 uv = (vec2(storePos.xy) + 0.5) / vec2(imageSize(skyboxStorage).xy); // Normalized coordinates
	uv = uv * 2.0 - 1.0; // Map to range [-1, 1]

	vec3 direction;
	switch (storePos.z) {
		case 0: direction = normalize(vec3(1.0,   -uv.y, -uv.x)); break; // +X
		case 1: direction = normalize(vec3(-1.0,  -uv.y,  uv.x)); break; // -X
		case 2: direction = normalize(vec3(uv.x,   1.0,   uv.y)); break; // +Y
		case 3: direction = normalize(vec3(uv.x,  -1.0,  -uv.y)); break; // -Y
		case 4: direction = normalize(vec3(uv.x,  -uv.y,  1.0));  break; // +Z
		case 5: direction = normalize(vec3(-uv.x, -uv.y, -1.0));  break; // -Z
		default: direction = vec3(0.0); break; // Should not happen
	}

	vec2 sphericalUV = SampleSphericalMap(normalize(direction));
	sphericalUV = clamp(sphericalUV, vec2(0.0), vec2(1.0));

	vec4 color = texture(equirectImage, sphericalUV);

	// Prevents overly bright spots, not physically accurate
	float maxL = max(max(color.r, color.g), color.b);
	if (maxL > 50.0) color *= 50.0 / maxL;

	imageStore(skyboxStorage, storePos, color);
}
